### ISSUE TITLE
Type not found

### ISSUE THREAD

**Issue by rrd108** [dereuromark/cakephp-decimal#5]
CakePHP 4.3.1 I installed the package via composer and added this to my `bootstrap.php` file

```php
Type::map('decimal', 'CakeDecimal\Database\Type\DecimalObjectType');
```

When I want to import `Type` my IDE offers the folowwing:
PHPUnit\Util\Type
SebastianBergmann\Type\Type
phpDocumentor\Reflection\Type
PharIo\Manifest\Type

In your tests you used `Cake\Database\Type` for what I get `Undefined type 'Cake\Database\Type'`

What do I miss?

**Comment by dereuromark** [comment]
Can you be more specific where those errors occur?

**Comment by rrd108** [comment]
Isn't it `TypeFactory::map('decimal', 'CakeDecimal\Database\Type\DecimalObjectType');` ?

**Comment by rrd108** [comment]
> Can you be more specific where those errors occur?

`/config/bootstrap.php`

But it seems just to be a false error of vscode, as I do not get any errors in the logs.

**Comment by rrd108** [comment]
Well, I am confused...

When I `get` an entity with associations and serialize the results all my decimal fileds remains as strings.

**Comment by dereuromark** [comment]
yes, because they automatically become strings in output if you do not use the object methods.
